# Generated by Django 3.1 on 2020-08-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgbl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationentry',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='kind',
            field=models.CharField(choices=[('bgbl1', 'BGBl Teil I'), ('bgbl2', 'BGBl Teil II')], max_length=25),
        ),
        migrations.AlterField(
            model_name='publicationentry',
            name='num_pages',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
